version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  target-branch: master
  allow:
  - dependency-type: development
  ignore:
  - dependency-name: "@babel/core"
    versions:
    - 7.12.17
